function result=inference2(X_test,col_num1_1,col_num2_1,row_num1_1,row_num2_1,error_matrix_im,error_matrix_un)
load net_parameter1;
[Tex,Tey,Tez,Tek]=size(X_test);
X_test=reshape(double(X_test),[Tex,Tey,Tez,Tek])/255;
                        %start
                         i_test=X_test;
                         i_test=i_test-mean_input;
                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                         batch1_feature=batch_normal(i_test,mean_b1,var_b1,...
                                        scale_b1,offset_b1);
                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                         conv1_feature=pointwise_fault2_conv(kernel_1,batch1_feature,bias_1,0,...
                                       error_matrix_im,error_matrix_un,col_num1_1,col_num2_1,row_num1_1,row_num2_1);
                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                         batch2_feature=batch_fault2_normal(conv1_feature,mean_b2,...
                                        var_b2,scale_b2,offset_b2,...
                                        error_matrix_im,error_matrix_un,col_num1_1,col_num2_1,row_num1_1,row_num2_1);
                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                         act1_feature=clip_relu(batch2_feature,6);
                          %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                         bottle1_feature=bottle_fault2_neck(act1_feature,0,1,kernel_2,kernel_3,...
                             kernel_4,bias_2,bias_3,bias_4,mean_b3,var_b3,scale_b3,offset_b3,...
                             mean_b4,var_b4,scale_b4,offset_b4,mean_b5,var_b5,scale_b5,offset_b5,6,...
                             error_matrix_im,error_matrix_un,col_num1_1,col_num2_1,row_num1_1,row_num2_1);

                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                         add1_feature=bottle1_feature+act1_feature;
                         max1_feature=max_pool(add1_feature,2);
                         row_num1_2=floor(row_num1_1/2);
                         row_num2_2=floor(row_num2_1/2);
                         col_num1_2=floor(col_num1_1/2);
                         col_num2_2=floor(col_num2_1/2);
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                         bottle2_feature=bottle_fault2_neck(max1_feature,0,1,kernel_5,kernel_6,...
                             kernel_7,bias_5,bias_6,bias_7,mean_b6,var_b6,scale_b6,offset_b6,...
                             mean_b7,var_b7,scale_b7,offset_b7,mean_b8,var_b8,scale_b8,offset_b8,6,...
                             error_matrix_im,error_matrix_un,col_num1_2,col_num2_2,row_num1_2,row_num2_2); 
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%      
                         add2_feature=bottle2_feature+max1_feature;
                         max2_feature=max_pool(add2_feature,2);
                         row_num1_3=floor(row_num1_2/2);
                         row_num2_3=floor(row_num2_2/2);
                         col_num1_3=floor(col_num1_2/2);
                         col_num2_3=floor(col_num2_2/2);
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                         bottle3_feature=bottle_fault2_neck(max2_feature,0,1,kernel_8,kernel_9,...
                             kernel_10,bias_8,bias_9,bias_10,mean_b9,var_b9,scale_b9,offset_b9,...
                             mean_b10,var_b10,scale_b10,offset_b10,mean_b11,var_b11,scale_b11,...
                             offset_b11,6,...
                             error_matrix_im,error_matrix_un,col_num1_3,col_num2_3,row_num1_3,row_num2_3); 
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                         add3_feature=bottle3_feature+max2_feature;
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                         global_feature=global_ave(add3_feature);
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                         global_feature1=reshape(global_feature,1,[],12630);
                         full_feature=fully_fault2(global_feature1,weight_ful1,bias_ful1,43,error_matrix_im);
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
                    full_feature=reshape(full_feature,43,12630);
                    [fx,~]=find(full_feature==max(full_feature,[],1));
                    result=fx;
end